site_name: Interface Designer
site_url: https://interface-designer.readthedocs.org
repo_url: https://github.com/Adminotech/fiware-interface-designer
site_description: Interface Designer Documentation
docs_dir: doc/
site_dir: html
markdown_extensions: [toc,fenced_code]
use_directory_urls: false
theme: readthedocs
extra_css: ["https://fiware.org/style/fiware_readthedocs.css"]
pages:
  - Home: index.md
  - 'Installation & Administration Manual': 'installation_administration.md'
  - 'User & Programmers Manual': 'user_programmers.md'
google_analytics: ['UA-83869420-2', 'http://interface-designer.readthedocs.io/']